// <auto-generated />
namespace StagingAreaConsoleAppV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_model1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_model1));
        
        string IMigrationMetadata.Id
        {
            get { return "202210291257461_update_model1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
